# version: "3.8"

services:
  app:
    build: images/nginx/${NGINX_VERSION}
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ./projects:/var/www/html/projects:cached
      - ./logs:/var/log/nginx:delegated
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    build: images/php/${PHP_VERSION}
    volumes: *appvolumes

  db:
    image: ${DB_VERSION}
    platform: linux/arm64/v8
    ports:
      - "3306:3306"
    env_file: env/db.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/dbdata:/var/lib/mysql:delegated

  # redis:
  #   image: ${REDIS_VERSION}
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redisdata:/data
  #   command: ["redis-server", "--appendonly", "yes"]

volumes:
  sockdata:
  ssldata:
  # redisdata:
