upstream fastcgi_backend {
  server unix:/sock/docker.sock;
}

server {
  listen 8000;
  return 301 https://$host$request_uri;
}

server {
  listen 8443 ssl;
  server_name test.local;

  ssl_certificate /etc/nginx/certs/nginx.crt;
  ssl_certificate_key /etc/nginx/certs/nginx.key;
  add_header Strict-Transport-Security "max-age=31536000" always;

  fastcgi_buffer_size 64k;
  fastcgi_buffers 8 128k;

  include /etc/nginx/conf.d/generated/projects.generated.conf;

  location = / {
    return 404;
  }

  location / {
    return 404;
  }

  location ~ \.php$ {
    return 404;
  }

  location ~ /\.ht {
    deny all;
  }
}
